//
//  Riddles.swift
//  RiddlesInTheDark
//
//  Created by Jaeson Booker on 9/6/19.
//  Copyright © 2019 Jaeson Booker. All rights reserved.
//

import Foundation

var questions: [String: String] = ["6/9/19":"You're a thief, and you've managed to break into the vault of an ancient bank filled with 100 sacks of coins. One of the sacks contains gold coins, while the other 99 are filled with counterfeit gold coins. You cannot tell the difference between the gold coins and the fakes by handling the coins, looking at them, biting them, or testing them.\n\nThe fake coins weigh exactly 1 ounce each, while the real gold coins weigh 1.01 ounces. There is a large scale with enough room for all the sacks in the vault, but as soon as you weigh something it will trigger an alarm, so you can use the scale just once before you must flee the vault.\n\nHow can you figure out which sack of coins contains the real gold by only weighing something on the scale once?\n\nCheck back tomorrow at midnight for the answer", "7/9/19": "Ten Perfectly Rational Pirate Logicians (PRPLs) find 10 (indivisible) gold pieces and wish to distribute the booty among themselves.\nThe pirates each have a unique rank, from the captain on down. The captain puts forth the first plan to divide up the gold, whereupon the pirates (including the captain) vote. If at least half the pirates vote for the plan, it is enacted, and the gold is distributed accordingly. If the plan gets fewer than half the votes, however, the captain is killed, the second-in-command is promoted, and the process starts over. (They’re mutinous, these PRPLs.)\n\nPirates always vote by the following rules, with the earliest rule taking precedence in a conflict:\n\nSelf-preservation: A pirate values his life above all else.\nGreed: A pirate seeks as much gold as possible.\nBloodthirst: Failing a threat to his life or bounty, a pirate always votes to kill.\n\nUnder this system, how do the PRPLs divide up their gold?\n\nCheck back tomorrow at midnight for the answer", "8/9/19": "What has roots as nobody sees,\nIs taller than trees,\nUp, up it goes,\nAnd yet never grows?\n\nCheck back tomorrow at midnight for the answer\n\nRiddle taken from The Hobbit", "9/9/19": "Voiceless it cries,\nWingless flutters,\nToothless bites,\nMouthless mutters.\n\nCheck back tomorrow at midnight for the answer\n\nRiddle taken from The Hobbit", "10/9/19": "It cannot be seen, cannot be felt,\nCannot be heard, cannot be smelt.\nIt lies behind stars and under hills,\nAnd empty holes it fills.\nIt comes out first and follows after,\nEnds life, kills laughter.\n\nCheck back tomorrow at midnight for the answer\n\nRiddle taken from The Hobbit", "11/9/19": "Alive without breath,\nAs cold as death;\nNever thirsty, ever drinking,\nAll in mail never clinking.\n\nCheck back tomorrow at midnight for the answer\n\nRiddle taken from The Hobbit", "12/9/19": "This thing all things devours;\nBirds, beasts, trees, flowers;\nGnaws iron, bites steel;\nGrinds hard stones to meal;\nSlays king, ruins town,\nand beats mountain down.\n\nCheck back tomorrow at midnight for the answer\n\nRiddle taken from The Hobbit"]
